-- Active: 1703365925535@@127.0.0.1@5433@postgres

--DROP SCHEMA IF EXISTS db CASCADE;
DROP TABLE IF EXISTS lists_items CASCADE ;

DROP TABLE IF EXISTS users_lists CASCADE ;

DROP TABLE IF EXISTS todo_lists CASCADE ;

DROP TABLE IF EXISTS users CASCADE ;

DROP TABLE IF EXISTS todo_items CASCADE ;
